CREATE TABLE questify_quests (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  quest_name TEXT NOT NULL,
  quest_desc TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP,
  completed BOOLEAN DEFAULT FALSE NOT NULL,
  quest_id INTEGER REFERENCES questify_users(id) ON DELETE SET NULL
);